### ISSUE TITLE
Missing folder specification

### ISSUE THREAD

**Issue by ThielNS** [kenjishiromajp/personal_boilerplate#1]
https://github.com/kenjishiromajp/personal_boilerplate/blob/3168ade333beb042fffd7549e665ee2e85954fc4/generators/index.js#L13

Today I was trying to create a new component using npm run generate and I got the following error:
 
__[FAILED] add ENOENT: no such file or directory, open '/Users/senai/Desktop/PROJETOS/react/boilerplate/personal_boilerplate/generators/component.js.hbs'__

I fixed it writing down the following code block:
`templateFile: './component/component.js.hbs',`

**Comment by wesleyramalho** [comment]
I had the same problem over here. Thanks for sharing the solution, @ThielNS!

**Comment by kenjishiromajp** [comment]
This problem was resolved! thanks for reporting it!
